apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo-test.fullname" . }}
  labels:
     {{- include "argo-test.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}